stages:
  - build
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt --cache-dir $PYTHON_CACHE_DIR

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - $PYTHON_CACHE_DIR 

build:
  stage: build
  image: python:3.10  
  script:
    - echo "Build stage"  
 
test:
  stage: test
  image: python:3.10
  script:
    - python -m unittest discover tests